# Different scRNA-seq datasets of Breast Cancer

## Download alternative single-cell data for breast cancer:

https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE180286

https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE167036

In [1]:
# GSE180286

import pandas as pd
import gzip
import os

file_name = "GSM5457213_E2020-3.expression_matrix.txt.gz"
file_path = os.path.join("./GSE180286_RAW/", file_name)

SC_df = pd.read_csv(file_path, sep="\t", compression="gzip")

SC_df

,TTGTTTCACTCC,TCCCCATTCACC,GTCCATTCGTCT,AAGCTTCTAAAT,CCCGGCCTCGCC,CTATTGGGATCT,TCCCCCTCGCTC,GGCTCGTCCCCG,TTTCAGCTCGAT,GTTGTGCTACGG,...,AAAAAATCTTAA,ACGTTGGCGGAC,ATGTGAGTGCGG,ATTTATATAAAC,CGCCTATGTCGG,CTCCAACCAATG,CTCCTGAAGCAC,GTACCAGCGGCA,TACCTCCTAAAG,TGGTTTGTAGGG
ARGLU1,6,0,5,1,6,3,2,1,0,4,...,0,0,0,0,0,0,0,0,0,1
MT-ND5,61,8,54,62,42,39,32,15,19,20,...,1,1,2,1,1,2,0,1,5,2
CCAR1,6,0,4,8,4,3,0,2,1,0,...,0,0,0,0,0,0,0,0,0,0
MALAT1,510,133,277,301,117,272,285,179,95,102,...,23,11,93,9,23,22,20,29,41,22
MT-RNR2,195,44,127,148,118,117,132,42,70,75,...,3,4,15,2,19,6,2,4,18,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ARSJ,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
SMIM32,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
MIR643,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AC008761.2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
SYNDIG1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
SC_df_T = SC_df.T
SC_df_T

,ARGLU1,MT-ND5,CCAR1,MALAT1,MT-RNR2,NPM1,NR3C2,CD2,PTPRN2,RPS27A,...,AC022509.1,VASN,RAD51AP1P1,RPL12P18,AL445222.1,ARSJ,SMIM32,MIR643,AC008761.2,SYNDIG1
TTGTTTCACTCC,6,61,6,510,195,41,0,4,0,47,...,0,0,0,0,0,0,0,0,0,0
TCCCCATTCACC,0,8,0,133,44,3,0,0,0,13,...,0,0,0,0,0,0,0,0,0,0
GTCCATTCGTCT,5,54,4,277,127,38,0,0,0,28,...,0,0,0,0,0,0,0,0,0,0
AAGCTTCTAAAT,1,62,8,301,148,27,0,5,0,23,...,0,0,0,0,0,0,0,0,0,0
CCCGGCCTCGCC,6,42,4,117,118,50,0,0,0,38,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CTCCAACCAATG,0,2,0,22,6,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
CTCCTGAAGCAC,0,0,0,20,2,0,0,0,0,4,...,0,0,0,0,0,0,0,0,0,0
GTACCAGCGGCA,0,1,0,29,4,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TACCTCCTAAAG,0,5,0,41,18,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TGGTTTGTAGGG,1,2,0,22,22,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [3]:
import anndata
import pandas as pd
import gzip
import os

filepath = '../dataset/Dataset32/Insitu_count.txt'

ST_df = pd.read_csv(filepath, sep='\t', encoding='utf-8')

ST_df

,CALR,S100A9,EFHD1,MYLK,ATP6V0E2,TXNL1,MUCL1,TYMP,KDM1A,SFRP1,...,CLDN4,MEST,ENY2,SEC61B,HSP90AA1,SET,RPS3,HLA-DRB1,EPCAM,NDUFB11
0,0,0,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,1,2,1,0,1,1,0,3,...,0,0,0,0,1,2,8,0,0,0
2,2,0,1,13,1,6,0,1,0,14,...,2,3,0,6,10,3,67,6,8,1
3,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,2,0,3,0,0,0
4,4,0,0,10,1,1,1,1,3,4,...,2,0,1,1,6,1,23,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1157,5,1,0,2,0,2,9,2,0,0,...,2,1,0,1,3,0,5,0,0,0
1158,6,1,2,4,1,2,7,3,0,0,...,3,2,1,0,12,3,8,3,0,2
1159,2,0,0,2,1,1,0,1,0,4,...,0,0,0,0,3,0,1,1,2,0
1160,3,0,0,0,0,0,2,1,0,1,...,0,1,0,1,6,0,4,2,0,1
1161,0,2,0,0,1,0,2,3,0,0,...,1,0,0,0,3,2,5,1,1,1

In [12]:
df_columns = set(SC_df_T.columns)
df_new_columns = set(ST_df.columns)

common_columns = df_columns.intersection(df_new_columns)
print(len(common_columns))

dataframe2_intersected = SC_df_T[list(common_columns)]

dataframe2_intersected

989

,TMEM9,KRT17,LGALS1,PLXDC2,SLC5A6,HLA-F,SRGN,MMP1,PTPRF,ANXA5,...,RPL22,BST2,FTH1,JUP,TMEM258,SLC7A2,CTSB,RPLP0,PPP2R1A,LAMTOR5
TTGTTTCACTCC,0,0,21,0,0,2,32,0,0,5,...,16,4,52,0,11,0,3,34,0,0
TCCCCATTCACC,0,0,2,0,0,0,0,0,0,1,...,3,1,6,0,2,0,0,2,0,0
GTCCATTCGTCT,0,0,18,0,0,0,18,0,0,4,...,16,4,27,0,12,0,1,25,3,3
AAGCTTCTAAAT,0,0,1,0,0,2,4,0,0,3,...,12,2,37,0,7,0,3,22,0,0
CCCGGCCTCGCC,0,0,0,0,1,1,7,0,0,4,...,11,1,16,0,3,0,2,40,0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CTCCAACCAATG,0,0,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,1,0,0
CTCCTGAAGCAC,0,0,0,0,0,0,0,0,0,0,...,0,0,2,0,1,0,0,2,0,0
GTACCAGCGGCA,0,0,0,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
TACCTCCTAAAG,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TGGTTTGTAGGG,0,0,0,0,0,0,0,0,0,0,...,0,0,3,0,0,0,0,1,0,0

In [13]:
import scanpy as sc

adata = sc.AnnData(dataframe2_intersected)

def leiden_clustering(adata, resolution=0.5, seed=1234):

    sc.tl.pca(adata, random_state=seed)
    
    sc.pp.neighbors(adata, random_state=seed)
    
    sc.tl.leiden(adata, random_state=seed, resolution=resolution)
    return adata

adata = leiden_clustering(adata, resolution=0.5, seed=1234)

adata

2025-03-03 21:51:53.629016: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-03-03 21:51:53.643847: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-03-03 21:51:53.643870: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-03-03 21:51:53.644321: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-03-03 21:51:53.647268: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-03-03 21:51:54.067504: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/tmp/ipykernel_2274130/3272739765.py:11: FutureWarning: In the future, the default backend for leiden will be igraph instead of leidenalg.

 To achieve the future defaults please pass: flavor="igraph" and n_iterations=2.  directed must also be False to work with igraph's implementation.
  sc.tl.leiden(adata, random_state=seed, resolution=resolution)

AnnData object with n_obs × n_vars = 6398 × 989
    obs: 'leiden'
    uns: 'pca', 'neighbors', 'leiden'
    obsm: 'X_pca'
    varm: 'PCs'
    obsp: 'distances', 'connectivities'

In [14]:
adata.write('./dataset/Dataset32/Review_scRNA_count_cluster_new0.h5ad')

# GSE167036

In [2]:
import pandas as pd
import numpy as np
from scipy.io import mmread

data_dir = "./GSE167036"
matrix_file = f"{data_dir}/GSE167036_cell_counts_matrix.mtx"
barcodes_file = f"{data_dir}/GSE167036_barcodes.csv.gz"
features_file = f"{data_dir}/GSE167036_features.csv.gz"

matrix = mmread(matrix_file).T

print(f"Matrix shape: {matrix.shape}")

barcodes = pd.read_csv(barcodes_file, compression='gzip', header=None, names=["barcodes"])
features = pd.read_csv(features_file, compression='gzip', header=None, names=["gene_symbols"])

print(f"Barcodes shape: {barcodes.shape}")
print(f"Features shape: {features.shape}")

if barcodes.shape[0] > matrix.shape[0]:
    print("Removing extra row from barcodes file.")
    barcodes = barcodes.iloc[1:]

if features.shape[0] > matrix.shape[1]:
    print("Removing extra row from features file.")
    features = features.iloc[1:]

print(f"Barcodes shape after cleaning: {barcodes.shape}")
print(f"Features shape after cleaning: {features.shape}")

if barcodes.shape[0] != matrix.shape[0] or features.shape[0] != matrix.shape[1]:
    raise ValueError("条形码或基因信息的行数与矩阵的行数或列数不匹配！")

df = pd.DataFrame(matrix.toarray(), index=barcodes["barcodes"], columns=features["gene_symbols"])

print("\nGenerated DataFrame:")

df

Matrix shape: (118845, 25301)
Barcodes shape: (118846, 1)
Features shape: (25302, 1)
Removing extra row from barcodes file.
Removing extra row from features file.
Barcodes shape after cleaning: (118845, 1)
Features shape after cleaning: (25301, 1)

Generated DataFrame:

gene_symbols,AL627309.1,AL669831.5,FAM87B,LINC00115,AL645608.7,AL645608.3,AL645608.1,SAMD11,NOC2L,KLHL17,...,AC003682.1,AC008079.1,AC246793.1,GGTLC2,AL021877.2,LINC00898,LINC01692,KRTAP19-8,CRYAA,LRRC3-DT
barcodes,,,,,,,,,,,,,,,,,,,,,
CA1_AAACCTGAGAGGTAGA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CA1_AAACCTGAGCCCAACC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CA1_AAACCTGAGCGTTTAC,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CA1_AAACCTGAGTCCGTAT,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CA1_AAACCTGCAAGTAATG,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
LN8_TTTGTCAGTCTCTCGT,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
LN8_TTTGTCAGTGGTCCGT,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
LN8_TTTGTCATCAAGATCC,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
LN8_TTTGTCATCACCGTAA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
LN8_TTTGTCATCATTTGGG,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
import pandas as pd

df_columns = set(df.columns)

df_new_columns = set(ST_df.columns)

common_columns = df_columns.intersection(df_new_columns)
print(len(common_columns))
dataframe2_intersected = df[list(common_columns)]

dataframe2_intersected

999

gene_symbols,RPS11,SPIB,EIF5A,RPL27,RPL22,SLC25A3,RGS1,SLPI,ME2,HTRA1,...,UQCRC1,IGHA1,MINOS1,DCDC2,NTN4,ISG15,SLC40A1,SAT1,STMN1,RPL4
barcodes,,,,,,,,,,,,,,,,,,,,,
CA1_AAACCTGAGAGGTAGA,6,0,0,3,3,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,2
CA1_AAACCTGAGCCCAACC,5,0,0,2,2,3,8,0,0,0,...,1,0,1,0,0,3,0,1,0,1
CA1_AAACCTGAGCGTTTAC,2,0,0,6,1,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
CA1_AAACCTGAGTCCGTAT,8,0,2,9,0,0,4,0,0,0,...,0,0,2,0,0,1,0,1,0,5
CA1_AAACCTGCAAGTAATG,5,0,4,12,20,9,0,0,0,12,...,1,0,5,0,0,5,0,9,0,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
LN8_TTTGTCAGTCTCTCGT,4,0,2,6,9,2,2,0,1,0,...,1,1,0,0,0,1,0,2,0,4
LN8_TTTGTCAGTGGTCCGT,1,0,0,1,2,5,3,2,0,0,...,1,0,1,0,0,0,0,5,0,2
LN8_TTTGTCATCAAGATCC,2,0,1,3,4,3,0,0,1,0,...,1,0,2,0,0,0,0,0,0,2
LN8_TTTGTCATCACCGTAA,0,0,0,2,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
LN8_TTTGTCATCATTTGGG,4,0,1,2,2,0,2,0,0,0,...,1,0,0,0,0,0,0,0,0,2

In [11]:
import scanpy as sc

adata = sc.AnnData(dataframe2_intersected)

def leiden_clustering(adata, resolution=0.5, seed=1234):

    sc.tl.pca(adata, random_state=seed)
    
    sc.pp.neighbors(adata, random_state=seed)
    
    sc.tl.leiden(adata, random_state=seed, resolution=resolution)
    return adata

adata = leiden_clustering(adata, resolution=0.5, seed=1234)

adata

/home/boom/.conda/envs/boom/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_csv from `anndata` is deprecated. Import anndata.io.read_csv instead.
  warnings.warn(msg, FutureWarning)
/home/boom/.conda/envs/boom/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_excel from `anndata` is deprecated. Import anndata.io.read_excel instead.
  warnings.warn(msg, FutureWarning)
/home/boom/.conda/envs/boom/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_hdf from `anndata` is deprecated. Import anndata.io.read_hdf instead.
  warnings.warn(msg, FutureWarning)
/home/boom/.conda/envs/boom/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_loom from `anndata` is deprecated. Import anndata.io.read_loom instead.
  warnings.warn(msg, FutureWarning)
/home/boom/.conda/envs/boom/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_mtx from `anndata` is deprecated. Import anndata.io.read_mtx instead.
  warnings.warn(msg, FutureWarning)
/home/boom/.conda/envs/boom/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_text from `anndata` is deprecated. Import anndata.io.read_text instead.
  warnings.warn(msg, FutureWarning)
/home/boom/.conda/envs/boom/lib/python3.11/site-packages/anndata/utils.py:429: FutureWarning: Importing read_umi_tools from `anndata` is deprecated. Import anndata.io.read_umi_tools instead.
  warnings.warn(msg, FutureWarning)
2025-02-21 17:36:33.988403: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-02-21 17:36:34.491290: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-02-21 17:36:34.491327: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-02-21 17:36:34.556292: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-02-21 17:36:34.706726: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-02-21 17:36:35.655488: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/tmp/ipykernel_471706/1233719404.py:16: FutureWarning: In the future, the default backend for leiden will be igraph instead of leidenalg.

 To achieve the future defaults please pass: flavor="igraph" and n_iterations=2.  directed must also be False to work with igraph's implementation.
  sc.tl.leiden(adata, random_state=seed, resolution=resolution)

AnnData object with n_obs × n_vars = 118845 × 999
    obs: 'leiden'
    uns: 'pca', 'neighbors', 'leiden'
    obsm: 'X_pca'
    varm: 'PCs'
    obsp: 'distances', 'connectivities'

In [13]:
adata.obs['leiden']

barcodes
CA1_AAACCTGAGAGGTAGA     1
CA1_AAACCTGAGCCCAACC     1
CA1_AAACCTGAGCGTTTAC     7
CA1_AAACCTGAGTCCGTAT     5
CA1_AAACCTGCAAGTAATG     6
                        ..
LN8_TTTGTCAGTCTCTCGT     0
LN8_TTTGTCAGTGGTCCGT     0
LN8_TTTGTCATCAAGATCC     6
LN8_TTTGTCATCACCGTAA    10
LN8_TTTGTCATCATTTGGG     1
Name: leiden, Length: 118845, dtype: category
Categories (18, object): ['0', '1', '2', '3', ..., '14', '15', '16', '17']

In [14]:
adata.write('./dataset/Dataset32/Review_scRNA_count_cluster_new1.h5ad')

## Using this dataset as the replacement scRNA-seq datasets, modify the code in option.py as follows: 

### self.opt.seq_data = os.path.join(self.opt.root, self.opt.dataset_name, 'Review_scRNA_count_cluster_new1.h5ad')